before_script:
  - apt-get update -qq && apt-get install -y hugo
  - hugo version

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
    - current

variables:
  GIT_SUBMODULE_STRATEGY: recursive
