before_script:
  - apt-get update -qq && apt-get install -y hugo
  - hugo version

deploy:
  environment: production
  stage: deploy
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
    - production